baseurl = "https://houfu.github.io/"
title = "Ang Hou Fu - Legal Technology Strategist"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Ang Hou Fu"
  info = "Practical tech solutions for resource-constrained legal teams"
  description = "Practical legal technology solutions and automation strategies for resource-constrained legal teams"
  keywords = "legal-tech,legal-automation,no-code,python,contract-automation,legal-programming,docassemble,legal-operations"
  # avatarurl = "images/avatar.jpg"
  gravatar = "damon.houf@gmail.com"

  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = "2019"
  commit = "https://github.com/houfu/houfu.github.io/"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/houfu/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/houfu/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/hou-fu-ang-0a6851113/"
[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 3
  url = "https://kopiti.am/@houfu"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-at fa-2x"
  weight = 4
  url = "mailto:houfu@outlook.sg"


[outputFormats]
  [outputFormats.SITEXML]
    mediaType = "application/xml"
    baseName = "site-export"
    isPlainText = true
    notAlternative = true


[outputs]
  home = ["HTML", "RSS", "SITEXML"] 

# Matomo
[params.matomo]
   siteID = "2"
   serverURL = "https://analytics.zeeker.sg"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
